stages:
  - build

variables:
  DOCKER_DRIVER: overlay2  # Improves performance.
  TERRAFORM_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

Build Docker image:
  stage: build
  only:
  interruptible: true
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker info
    - docker -D login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker -D build -t $TERRAFORM_IMAGE_NAME .
    - docker -D push $TERRAFORM_IMAGE_NAME
  only:
    - develop